### ISSUE TITLE
Can't run serve

### ISSUE THREAD

**Issue by gnutix** [canderis/RevanEditor#12]
> npm run serve
```
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gnutix/.npm/_logs/2020-01-11T14_40_02_400Z-debug.log
```

I can build the project, but just running `dist/index.html` in a browser just hangs on "Loading..." with errors in the console like : 

```
Access to script at 'file:///runtime-es2018.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
/runtime-es2018.js:1 Failed to load resource: net::ERR_FAILED
```

**Comment by canderis** [comment]
I made a dumb typo in the readme! Should be "npm run dev"!

**Comment by gnutix** [comment]
```
$ npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gnutix/.npm/_logs/2020-01-14T20_13_42_479Z-debug.log
```

As I said, I wouldn't mind helping. But it would really be nice if you could provide me the basic steps to run the project on a local web server (which commands to run to install all the node modules, and which commands to run to build / serve the app).

There's tons of commands in `package.json` and I'm really not sure which to use. Tried `ng:serve`, `start`, `ng:serve:web`, none worked.

**Comment by canderis** [comment]
Really sorry, i made a really stupid mistake. I was looking at the wrong project. Again.

It should be "npm start". If that doesn't work, there's something else at issue I'm missing but that should work.

**Comment by gnutix** [comment]
OK, `npm start` runs the Electron window. Now we're getting somewhere.
